# Generated by Django 4.2.13 on 2024-06-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
